chapter_2
music-flo-junior/kafka-study pull request #4
Opened 2024-12-05 02:03 UTC by ha0kim97

2024-12-05 07:34 UTC, jiaekim123 requested changes

2024-12-05 07:34 UTC, jiaekim123 commented on docs/chapter_2.md
> +- X : 셔벼의 ID ( 정수값이기만 하면 됨. 0부터 시작할 필요도 없고 순차적으로 부여될 필요도 없음)
```suggestion
- X : 서버의 ID ( 정수값이기만 하면 됨. 0부터 시작할 필요도 없고 순차적으로 부여될 필요도 없음)
```

2024-12-06 02:31 UTC, woo-wook approved these changes

2024-12-06 02:31 UTC, woo-wook commented on docs/chapter_2.md
> +- (우리는 개발은 3 / 상용은 5개로 하는듯..? 이유가 뭘까? 생각해본 사람~~?)
기록차 남겨두자면 브로커의 수 😮

2024-12-11 02:05 UTC, merged